
install:
	pip install -r requirements.txt




test-riccardo:
	./main.py "inputs/medium-latest-articles.palladiusbonton.metadata.json" \
		"inputs/medium-latest-articles.palladiusbonton.txt.cleaned.json"
